jobs:
  include:
    - stage: Test py37
      language: python
      python: 3.7
      install: pip install tox-travis
      script: tox -e py37
    - stage: Test py38
      language: python
      python: 3.8
      install: pip install tox-travis
      script: tox -e py38
    - stage: Test py39, coverage, deploy
      language: python
      python: 3.9
      install: pip install tox-travis pytest coverage
      script:
        - tox -e py39
        - coverage run -m pytest
      after_success: bash <(curl -s https://codecov.io/bash)
      deploy:
        provider: pypi
        distributions: sdist bdist_wheel
        user: "__token__"
        password:
          secure: uLdjVCqJIyXtJHMssDNTvDfWmYP17f9GPggPNyqI1Mwu0wjZxgWKTHWJpQ3c9+0XA7Zzz4qO5Qds0ME7rtZSkd3eXEcBzNBr+/CG29Jy0cHM9++HigQ2RaPODuZQsM5+8SzmibZjA/v7M0WwDeouMktbYLE2e0WMLEzzAtKuAwnnK27z3JBmNQ+8Eda3G/sUuYHpV8tPSHnc+NrxGfe7AEEtEO/+CHuGL+QBEOoqA2cMjL13ndybo7yVVTch+m8Ierb6/L3bokkOWeHzgi8E8DmoR+XWAeoPbb1w1BC1e3VtUGKs+Uph8sdVc7tVw58We0AD75r1PwWb830k54hQ+I4pt2KBmAyghXD8hUAETVGzcOts/SsbbZ0YtqB3T4b0sopCno9VjO5rlndJv7SxvQ6aO9xAu6bU6iyofZfKrle86KZAEdcvX5oYfnT2YHdMGKjISOnP8JU7LvBcCqFb4nsyKLClTKWY5beBxsO/XJYhMpvg405JbEIMn5fHLqS2ZT/WjkZ3ailShzo+d6VCEqMpktIDkotBwq5bzzpWs3XWFr+Xer8a74O0YCaRKmaJsKQlAeSkCfyHBFxX8YIzT7Z9U/yxGDUNhBpIkEUNRgwwkklyH83SZD62b0CUUJuakHNd83ws/y+s7GKCKWXBCL/ArRk0cl4mu8+erBCNBNE=
        on:
          tags: true
          repo: hanifbirgani/codemelli
          python: 3.9
branches:
  only:
    - main
    - /^v\d+\.\d+(\.\d)?$/
